### ISSUE TITLE
investigate a warning pop up in trivia screen 

### ISSUE THREAD

**Issue by duonghv1** [UCI-Capstone-Paciolan-2024/PacTrivia#18]
![image](https://github.com/UCI-Capstone-Paciolan-2024/PacTrivia/assets/76922255/17f6607d-b653-4804-b923-67d9a07df162)
![image](https://github.com/UCI-Capstone-Paciolan-2024/PacTrivia/assets/76922255/5b8af613-e890-4a10-a0cb-a6c5efe9f5fe)

**Comment by typhocannon** [comment]
The warning is from Progress.Circle in the TimerBar component

**Comment by typhocannon** [comment]
Commenting out Progress.Circle fixes the issues, but even though adding collapsable={true} the warning pop up is still raised

**Comment by cokwong** [comment]
Seems like an internal issue with the Circle prop.
