### ISSUE TITLE
margin issue in landing page

### ISSUE THREAD

**Issue by dylanvu** [UCI-Capstone-Paciolan-2024/PacTrivia#6]
Add some margins to the landing page.

![Image](https://github.com/UCI-Capstone-Paciolan-2024/PacTrivia/assets/75911565/8c2150c0-2cda-4479-a86f-41e2e36a1e33)

**Comment by duonghv1** [comment]
resolved with the latest commit in main 5a2548c8f9b5ffdf64dd21a6781a45d84d776630. 

currently looking like this:
![image](https://github.com/UCI-Capstone-Paciolan-2024/PacTrivia/assets/76922255/a833cd2a-a189-4ca1-bfa5-3939b86ad156)
